### ISSUE TITLE
Add as npm package

### ISSUE THREAD

**Issue by rollecode** [RazvanDH/breakpoints#4]
Hello! Thanks for the mixin. It would be great to be able to use this directly from upstream. Didn't find a npm package yet, can you create one?

**Comment by RazvanDH** [comment]
Hey @ronilaukkarinen . Sorry for the late feedback, but I finally added this as an `npm` package.

`npm install rs-breakpoints` should do the trick now :)

Thanks for the suggestion!

**Comment by rollecode** [comment]
Thank you @RazvanDH! I really appreciate it.
